-- Add migration script here
CREATE TABLE urls (
    id VARCHAR(10) PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    clicks INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
